### ISSUE TITLE
How to set AUv3 target?

### ISSUE THREAD

**Issue by horho77** [eyalamirmusic/JUCECmakeRepoPrototype#10]
Thanks for making the cmake templates. They are very useful.
How do you go about making an AUv3 target? Based on the JUCE cmake info, it should be possible to build as AUv3. Adding the "AUv3" to the cmake "FORMATS AU VST3 Standalone" section doesn't make it available in CLion's target section though. Any advice would be appreciated...

**Comment by eyalamirmusic** [comment]
Are you referring to AUv3 plugin for iOS?

**Comment by horho77** [comment]
Not necessarily, I mean the general AUv3 for all Apple platforms. The audio plugin is in the application extension *.appex format. Projucer -> Xcode produces the binary fine when selecting the AUv3 option.

**Comment by eyalamirmusic** [comment]
That's a good point, I think it might be worth it to report it to the JUCE team.
I found that if you're using the Xcode exporter in CLion (add -G Xcode to the CMake option under preference->build->CMake) it does bring the AUv3 in there, so it looks like AUv3, at least in the way JUCE has it, requires a specific toolchain. Maybe it's a mistake? I'll report.

BTW, out of interest, what's your use case for creating AUv3 for non-iOS?

**Comment by eyalamirmusic** [comment]
I asked reuk from the JUCE team and they confirmed that this is how it should be (Xcode exporter only).

**Comment by horho77** [comment]
Thank you very much for responding!
Taken from [Migrating Your Audio Unit Host to the AUv3 API](https://developer.apple.com/documentation/audiotoolbox/audio_unit_v3_plug-ins/migrating_your_audio_unit_host_to_the_auv3_api):

"A key difference between the two audio unit API versions is that AUv2 audio units are loaded into the host's process, whereas AUv3 audio units are loaded out-of-process by default. In macOS only, if supported by the AUv3 audio unit, you can request loading it in-process by passing the loadInProcess option in the options argument. To verify that the audio unit was successfully loaded in-process, query its isLoadedInProcess property."

I just wanted to use the latest format of AU, the main reason being the v3 running on separate thread would not affect the host when having any problems...

**Comment by horho77** [comment]
I'm happy. We can close this if you want...

**Comment by eyalamirmusic** [comment]
Actually AUv2 can now also be loaded out of process, Logic does it and your own hosts can do that too.

**Comment by horho77** [comment]
Ahhh. Didn't know that. Thanks. 
I'm happy with the info. I can always export to Xcode if I really need v3...
