### ISSUE TITLE
Visual Studio compilation failed

### ISSUE THREAD

**Issue by tawfik741** [eyalamirmusic/JUCECmakeRepoPrototype#11]
I tried to compile it with visual studio

I started by removing:
```
#set(CMAKE_OSX_DEPLOYMENT_TARGET "10.9" CACHE STRING "Minimum OS X deployment version" FORCE)
```

I then ran `cmake .`  and tried to compile it with visual studio but I get compiler errors.

![image](https://user-images.githubusercontent.com/37041878/131407836-71dbb79a-5f6e-4a75-a2e5-269c9681af10.png)

all pointing to this line in `Microsoft.CppCommon.Targets` 
```
    <Exec Command="%(PostBuildEvent.Command)$(_BuildSuffix)" StdOutEncoding="%(PostBuildEvent.StdOutEncoding)" StdErrEncoding="%(PostBuildEvent.StdErrEncoding)" Condition="'%(PostBuildEvent.Command)' != ''"/>
```

**Comment by eyalamirmusic** [comment]
Hey, thanks for reporting!
1. You shouldn't need to remove that variable setting. On non-Apple systems it just does nothing.
2. For Visual Studio you need to use the MSVC generator, so the full command line is:
```
git clone https://github.com/eyalamirmusic/JUCECmakeRepoPrototype.git JUCERepo
cd JUCERepo
cmake -G "Visual Studio 16 2019" -B build
```
Then under 'build' you'll find a working VS solution (just tested).

Alternatively, VS2019 now supports CMake natively too, so you can just File->Open->CMake and open the repo directory directly without ever running CMake from the command line.

Hope that helps!
Eyal

**Comment by tawfik741** [comment]
Hi @eyalamirmusic , I've been trying to figure out what's now working correctly for the past days but even running your script I still can't get to build the directories above. 

![image](https://user-images.githubusercontent.com/37041878/132003658-13af4732-4068-4b21-afe7-9a4afbeb8794.png)
![image](https://user-images.githubusercontent.com/37041878/132003709-d9048d55-84d0-4b96-a11c-2b14c10f5a03.png)

**Comment by eyalamirmusic** [comment]
Can you please try the following:
1. Delete any old cloned.
2. Run the exact command line I wrote above in that exact order.
3. Look at the CMake print and see if it shows any errors, if it does post them here
4. Try opening the solution under JUCERepo/build

**Comment by tawfik741** [comment]
Ok, I solved the issue. After some more debugging I found out it was due to the fact that visual studio was not running in administrator mode and couldn't write to `C:/program files` which made the build to fail

**Comment by eyalamirmusic** [comment]
Ah, so it failed on the post build, when it tried to copy the plugin file?

Yes, that makes sense.

To solve it, you don't need to run VS as administrator.
Instead, you right click on these target folders (Program Files\Common Files\VST3)
And set the security settings of that folder to allow read/write from all users.

**Comment by tawfik741** [comment]
exactly it was a post build issue,

should I make a pull request where I update the `README.md` regarding this issue?

**Comment by eyalamirmusic** [comment]
I'll update it with some notes on that, thanks. :)
