### ISSUE TITLE
juce-populate not found

### ISSUE THREAD

**Issue by karlvignon** [eyalamirmusic/JUCECmakeRepoPrototype#12]
I am on windows 10 on CLion using Ubuntu-20.04 as a terminal.
Everything compiles correctly: all plugins and applications are compiled.
But it displays this error in Cmake console of CLion : 

`-- CPM: adding package JUCE@ (origin/develop)
CMake Error at /cygdrive/c/Users/ArKen/AppData/Local/JetBrains/CLion2021.2/cygwin_cmake/share/cmake-3.20.2/Modules/ExternalProject.cmake:2633 (message):
  error: could not find git for clone of juce-populate
Call Stack (most recent call first):
  /cygdrive/c/Users/ArKen/AppData/Local/JetBrains/CLion2021.2/cygwin_cmake/share/cmake-3.20.2/Modules/ExternalProject.cmake:3681 (_ep_add_download_command)
  CMakeLists.txt:22 (ExternalProject_Add)`

**Comment by eyalamirmusic** [comment]
Hey! Thanks for reporting.

JUCE has a lot of weird problems with Cygwin/MinGW. See if you can configure CLion to use the Visual Studio or Clang toolchains instead.

**Comment by karlvignon** [comment]
Everything finally work with WSL instead of Cygwin! Thank you so much :) 
(For the ones coming after: https://www.jetbrains.com/help/clion/how-to-use-wsl-development-environment-in-product.html)
