### ISSUE TITLE
Universal binary creation failed

### ISSUE THREAD

**Issue by martinstolz-ch** [eyalamirmusic/JUCECmakeRepoPrototype#13]
First of all: Thanks for the great example projects!

In osx the creation of "universal binary" fails. 
In the top CMakeLists.txt I changed the line

_**option(UniversalBinary "Build universal binary for mac" [ OFF | ON ] )**_

to 

**_option(UniversalBinary "Build universal binary for mac" [ FALSE | TRUE ] )_**

This can create an AU plugin that is recognized in Logic with both apple silicon and i64 (Rosetta mode).

**Comment by eyalamirmusic** [comment]
Hey! That's very strange. 
"ON" should be recognized as a boolean option in CMake.
When I manually changed the word "OFF" to "ON", and then re-ran CMake and built the console app template (or any other one), I got a universal binary which I verified with:
`lipo -archs ConsoleAppTemplate`
 
 Also, you can pass this flag when running CMake and not change the CMake file by doing
 `CMake -G Xcode -B build -D UniversalBinary=1`
 That also works for me, and a little better as universal binaries take 2x to build, so I only it when I deploy but not when I debug locally.

**Comment by martinstolz-ch** [comment]
Yes, my mistake, sorry! I only relied on the plugin scan from Logic and probably disregarded the boundary conditions for a reliable scan.
