### ISSUE TITLE
Thoughts on make this repo a Template Repository

### ISSUE THREAD

**Issue by JeffersonBledsoe** [eyalamirmusic/JUCECmakeRepoPrototype#4]
GitHub has a feature which allows users to easily copy the template and start a new repo from it, without forking. This repo seems like it would be great to have this feature available. GitHub has some simple [docs for enabling template repositories](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository) and [creating template repositories](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template) available on it's docs site.

Great work on this, it was just the head-start I needed to get back into JUCE while simultaneously learning CMake!

**Comment by eyalamirmusic** [comment]
Hey @JeffersonBledsoe, thank you so much for your comment!

I agree, just switched the repo to be a template!

**Comment by JeffersonBledsoe** [comment]
Great stuff! Keep up the good work!
