### ISSUE TITLE
CMake Error when specifying location of JUCE in CLion

### ISSUE THREAD

**Issue by CSPilly** [eyalamirmusic/JUCECmakeRepoPrototype#6]
I tried to set up this in CLion using a local folder for JUCE and I get A CMake error when building juceaide:

![image](https://user-images.githubusercontent.com/50848932/115680899-e680af80-a34b-11eb-9d9c-2b42380df5a8.png)

My CMake settings are the following:

![image](https://user-images.githubusercontent.com/50848932/115681011-04e6ab00-a34c-11eb-88da-5ea81f2f3a77.png)

**Comment by eyalamirmusic** [comment]
That's interesting, what happens if you remove the flag and let CPM grab JUCE from git? Does it still show the same errors?

**Comment by CSPilly** [comment]
Hi there, if I remove the flag it seems to work fine!

**Comment by mrdvince** [comment]
Experiencing the same issue.

**Comment by eyalamirmusic** [comment]
I think this is related to MinGW which has some issues. Try switching to MSVC or Clang (which are way better anyway).

**Comment by eyalamirmusic** [comment]
Also, you might want to clear the build folder while the project is not open in CLion after changing that flag.

**Comment by QuantScientist** [comment]
I amended the CMake file as follows:

```
CPMAddPackage(
	SOURCE_DIR ${CMAKE_SOURCE_DIR}/JUCE
        NAME JUCE        
        )
```

Other than that, I made no changes in CLion:
![image](https://user-images.githubusercontent.com/18743986/124276180-259d5f00-db4c-11eb-95ff-d2080f2139dd.png)


Hope this help,

**Comment by eyalamirmusic** [comment]
Thanks @QuantScientist! I was not aware of this feature, gonna try it in a bit!
