### ISSUE TITLE
Plugin Build failure

### ISSUE THREAD

**Issue by CSPilly** [eyalamirmusic/JUCECmakeRepoPrototype#7]
Trying to build the NewPluginTemplate on windows in CLion using MinGW. The target will not build. Nothing has been done to the repo.

`Z:\Tutorials\JUCECmakeRepoPrototype\cmake-build-debug\_deps\juce-src\modules\juce_audio_formats\juce_audio_formats.cpp:51:11: fatal error: wmsdk.h: No such file or directory
  #include <wmsdk.h>
           ^~~~~~~~~
compilation terminated.`

**Comment by eyalamirmusic** [comment]
I think this might be a bug in JUCE and MinGW.
I'd really suggest to build JUCE-related things with either MSVC or Clang (not just for this reason)

**Comment by CSPilly** [comment]
Ah okay, I didn't realise that MinGW was a bit flaky with JUCE, I'll give everything else a run using MSVC

**Comment by CSPilly** [comment]
yep, literally runs like a dream now! Really sorry, thanks so much for your help!
