### ISSUE TITLE
LV2 support?

### ISSUE THREAD

**Issue by mxmilkiib** [eyalamirmusic/JUCECmakeRepoPrototype#8]
https://jatinchowdhury18.medium.com/building-lv2-plugins-with-juce-and-cmake-d1f8937dbac3

**Comment by eyalamirmusic** [comment]
As you may know, LV2 is not officially supported in JUCE (and therefore not supported by this example repo).

However, you can definitely set CPM in your top CMakeLists.txt to point at the fork that Jatin made:
```
CPMAddPackage(
        NAME JUCE
        GITHUB_REPOSITORY lv2-porting-project/JUCE
        GIT_TAG origin/master)
```
Hope that helps!
